### ISSUE TITLE
Bug: some builds are inspected but are not recorded in the spreadsheet (these data can be found in the csv file).

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/librepair#201]
We get the following exception when the build is not recorded in the spreadsheet:
```
03:09:45.048 [main] ERROR f.i.s.r.s.e.t.GoogleSpreadsheetSerializerEngine - An error occurred while inserting data in Google Spreadsheet.
com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at fr.inria.spirals.repairnator.serializer.gspreadsheet.GoogleSpreadSheetFactory.insertData(GoogleSpreadSheetFactory.java:81)
	at fr.inria.spirals.repairnator.serializer.engines.table.GoogleSpreadsheetSerializerEngine.serialize(GoogleSpreadsheetSerializerEngine.java:35)
	at fr.inria.spirals.repairnator.serializer.InspectorSerializer4Bears.serializeData(InspectorSerializer4Bears.java:119)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.serializeData(AbstractStep.java:152)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.terminatePipeline(AbstractStep.java:246)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:240)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:142)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:238)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:142)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:238)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:142)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:238)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:142)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:238)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector4Bears.run(ProjectInspector4Bears.java:78)
	at fr.inria.spirals.repairnator.pipeline.Launcher.mainProcess(Launcher.java:389)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:397)
```

**Comment by surli** [comment]
This is caused by the concurrent usage of google access token. Don't know yet how to solve it. But data are available elsewhere.

**Comment by fermadeiral** [comment]
Ok. I just wanted to record the existence of this issue here.
