### ISSUE TITLE
implement repair attempt in travis directly

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#374]
using `maven npefix`
and
`maven nopol/astor` to be implemented

**Comment by surli** [comment]
Related to #301

**Comment by monperrus** [comment]
simply adding maven-repair in the pom would trigger repair attempts when a test case fails.

(maven-repair would register to the surefire events)

**Comment by monperrus** [comment]
Link https://github.com/eclipse/repairnator/tree/master/src/maven-repair

**Comment by cokefh** [comment]
I'm working on it. FH

**Comment by monperrus** [comment]
@cokefh what's the progress here?

**Comment by monperrus** [comment]
There are two files to modify for doing this for NPEFix

* https://github.com/eclipse/repairnator/blob/master/src/maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/AbstractRepairMojo.java
* https://github.com/eclipse/repairnator/blob/master/src/maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NPEFixMojo.java

**Comment by monperrus** [comment]
Today we must run the tests first and the run the repair attempt:

```
mvn test -DtrimStackTrace=false
mvn fr.inria.gforge.spirals:repair-maven-plugin:npefix
```

With the change, when the maven plugin is setup in pom.xml, only `mvn test` would be necessary, upon failures, the repair attempt would be started automatically.

```
mvn test
```

If a patch exists, it would be outputted on the console.

**Comment by monperrus** [comment]
Reference documentation: https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag

**Comment by monperrus** [comment]
FYI: deflaker does something similar: https://github.com/gmu-swe/deflaker

**Comment by monperrus** [comment]
See https://github.com/gmu-swe/deflaker/blob/master/maven-extension/src/main/java/org/deflaker/maven/DeflakerLifecycleParticipant.java

**Comment by monperrus** [comment]
Two kinds of extensions:
* Maven lifecycle extensions, see https://maven.apache.org/examples/maven-3-lifecycle-extensions.html (we would like to extend the phase test)
* Surefire extensions (see below)

## Maven lifecycle extensions

* Example of configuration: See bottom of https://maven.apache.org/examples/maven-3-lifecycle-extensions.html and [deflaker readme](https://github.com/gmu-swe/deflaker/)
* Example of code: https://github.com/gmu-swe/deflaker/blob/master/maven-extension/src/main/java/org/deflaker/maven/DeflakerLifecycleParticipant.java

## Surefire extensions

Potential [extension points of surefire](https://github.com/apache/maven-surefire/blob/eb48f1b59ca5ccf6954ef33ecab03dbaf93214cd/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/CommonReflector.java):
`startupReportConfiguration`; `consoleLogger`; `statelessTestsetReporter`; `consoleOutputReporter`; `statelessTestsetInfoReporter`; `surefireClassLoader`
(not documented in code)
(not documented in https://maven.apache.org/surefire/surefire-extensions-api/)

Example of surefire extension configuration:
https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/blob/master/pom.xml#L92

Example of class extending JUnit5StatelessTestsetInfoReporter
https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/blob/bed1975a6b1a4cff3ae87df5d9a6c727f2396bce/src/main/java/org/apache/maven/plugin/surefire/extensions/junit5/JUnit5StatelessTestsetInfoTreeReporter.java

**Comment by monperrus** [comment]
To get the current live documentation of the plugin:

    mvn help:describe -DgroupId=fr.inria.gforge.spirals -DartifactId=repair-maven-plugin -Ddetail=true

It clearly shows that the repair goals are already bound to phase `test`

```
repair:npefix
  Description: (no description available)
  Implementation: com.github.tdurieux.repair.maven.plugin.NPEFixMojo
  Language: java
  Bound to phase: test

  Available parameters:

    javaVersion (Default: -1)
      User property: java.version
      (no description available)

    localRepository (Default: ${localRepository})
      (no description available)

    nbIteration (Default: 100)
      Required: true
      User property: laps
      (no description available)

    oldSource (Default: -1)
      User property: maven.compile.source
      (no description available)

    outputDirectory (Default: ${project.build.directory}/npefix)
      Required: true
      User property: outputDir
      Location of the file.

    repairStrategy (Default: default)
      Required: true
      User property: strategy
      (no description available)

    resultDirectory (Default: ${project.build.directory}/npefix)
      Required: true
      User property: resultDir
      (no description available)

    scope (Default: class)
      Required: true
      User property: scope
      (no description available)

    selector (Default: exploration)
      Required: true
      User property: selector
      (no description available)

    source (Default: -1)
      User property: maven.compiler.source
      (no description available)

```

**Comment by monperrus** [comment]
Who calls NPEFixMojo.execute?

```
	at com.github.tdurieux.repair.maven.plugin.NPEFixMojo.execute(NPEFixMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

```

**Comment by monperrus** [comment]
The solution is probably to configure either or both the `pom.xml` of maven-repair or the `pom.xml` of the program under repair.

**Comment by cokefh** [comment]
Here I think we may need to modify both the maven-repair pom.xml file and the project pom.xml file, for the sake of tidyness of project pom.xml.

**Comment by monperrus** [comment]
To check that a plugin is well bound:

```
mvn fr.jcgay.maven.plugins:buildplan-maven-plugin:list

-----------------------------------------------------------------------------------------
PLUGIN                 | PHASE                  | ID                      | GOAL         
-----------------------------------------------------------------------------------------
maven-resources-plugin | process-resources      | default-resources       | resources    
maven-compiler-plugin  | compile                | default-compile         | compile      
maven-resources-plugin | process-test-resources | default-testResources   | testResources
maven-compiler-plugin  | test-compile           | default-testCompile     | testCompile  
maven-surefire-plugin  | test                   | default-test            | test         
repair-maven-plugin    | test                   | execution2sfsdfsdfgsdfg | npefix       
maven-jar-plugin       | package                | default-jar             | jar          
maven-install-plugin   | install                | default-install         | install      
maven-deploy-plugin    | deploy                 | default-deploy          | deploy       
```

repair-maven-plugin is there!

**Comment by monperrus** [comment]
Yet, repair-maven-plugin is skipped if the previous goal (maven-surefire-plugin:default-test) fails.

This contradicts what we want to do!

**Comment by monperrus** [comment]
Next steps:

With -Dmaven.test.failure.ignore=true the build does not fail if there is a test failure, which is the opposite of what the users want. Solutions:

**First**, we never want to fail the build if there is an error during the repair process, so we'll add a try-catch block around the repair code

```java
try {
  .... repair
} catch (Exception e) {
  Log.info();
}
```

We have do this for all repair goals but we'll do it for npefix first.

**Second**, we have to fail the build if there one one test failure:

```java
// at the end of execute

if (thereWasAtLeastOneTestFailure()) {
  throw new RuntimeException("there was one test failure"); // may be one specific MojoException or SurefireException
} else {
  // do nothing
}
```

**Comment by monperrus** [comment]
FTR, #1106 does this for NpeFix

**Comment by monperrus** [comment]
For supporting this feature in the other repair tools, we need to do a refactoring.

AbstractRepairMojo.java would be the only class to override `execute` from the Maven framework, in order to do the test checks / try-catch / rethrow failures. It would also declare an absract method `executeRepair`.

Each Mojo would implement `executeRepair`.
